name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build-test-typecheck:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test

      - name: Type Check
        run: bun run typecheck
